import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "./components/SideBar";
import {Providers} from "./providers"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="flex h-screen">

             {/* サイドバー */}
             <aside className="hidden md:flex flex-col w-1/6 h-full border-r border-foreground/10 px-4 py-6">
              <SideBar />
            </aside>

             {/* メインコンテンツ */}
              <main className="flex-1 p-6 overflow-auto">
               {children}
             </main>

          </div>

          <div className="md:hidden">
            <SideBar />
          </div>

        </Providers>
      </body>
    </html>
  );
}
